server:
  port: 8081

spring:
  data:
    mongodb:
      host: productdb
      port: 27017
      database: ms_product
      username: root
      password: root
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/authentication

eureka:
  instance:
    hostname: ms-product
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      manufacturerClient:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s


logging:
  level:
    com.store.product: DEBUG
